### ISSUE TITLE
Remove Contributors section from readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/sqlite3-promisify#18]
We need to remove `Contributors` section from readme. Since github shows the contributors list on right sidebar.

**Comment by WanjohiWanjohi** [comment]
Hello @arshadkazmi42  
Raised a PR for this.
Let me know if this works for you

**Comment by raimeenakshi** [comment]
Hi @arshadkazmi42 Please assign this Issue to me.
PR - https://github.com/arshadkazmi42/sqlite3-promisify/pull/20
