### ISSUE TITLE
Example in readme does not work.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [arshadkazmi42/sqlite3-promisify#7]
Example does not work minor errors.
DB_PATH not defined.

Fixed
const DB_PATH = __dirname + '/sqlite3.db';

Then it gives
(node:23548) UnhandledPromiseRejectionWarning: ReferenceError: SQLiteCrud is not defined

Names are wrong should be SqliteCrud and Db.all Db.get

Then got "Error table does not exist" of course (looking at it, it would exist I ran the tests for sample data)

Node v13.5.0

**Comment by arshadkazmi42** [comment]
Good catch. I didn't notice these. Thanks for reporting
